development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: kabuni-dev
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: kabuni-test
  pool: 5
  username: root
  password: root
