# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f4417b69f9244cc04adbbb97a35b4913733b0252f8a08eb68f159cadde7e53c9dcf6299d2c2f91fcc66671d7f7dbb566494264d3796969e1d16fbcb64ceedf3

test:
  secret_key_base: 3307d4be529015c9e4180fc777f1895e6b7e14094c2f8462b470b9ca83e6737fd2dce7c2da8de023609a3a3ed7f6b41da8a0014de36977f09230eab3b463e1bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
